version: "3"
services: 
  springboot-app:
   # container_name: spring-app
    image: springbooot-app
    restart: always
    build: .
    ports:
      - 8000:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 2580
      MYSQL_PORT: 3306
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      -  /devopsproj/db:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: full-stack-ecommerce
      MYSQL_ROOT_PASSWORD: 2580
        